from models.utils import ModelType
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from models.positional_encoding import build_spatial_only_pe
from models.st_transformer import STTransformer


def timestep_embedding(t, dim):
    # sinusoidal embedding of a flow time t in [0, 1] (scaled by 1000 like DiT): [...] -> [..., dim]
    half = dim // 2
    freqs = torch.exp(-math.log(10000.0) * torch.arange(half, device=t.device, dtype=torch.float32) / half)  # [dim/2]
    args = t.float()[..., None] * 1000.0 * freqs  # [..., dim/2]
    return torch.cat([torch.cos(args), torch.sin(args)], dim=-1)  # [..., dim]


def shift_noise_level(s, shift):
    # timestep shift of Esser et al. (SD3) on the noise level s in [0, 1] (s = 1 pure noise): shift > 1 spends more
    # training steps / sampling steps at high noise; shift = 1 is the identity
    return shift * s / (1 + (shift - 1) * s)


class FlowDynamicsModel(nn.Module):
    """Flow-matching dynamics (STA-28): same causal ST-transformer as DynamicsModel, but the last frame's FSQ latents are
    generated by integrating a velocity field from Gaussian noise instead of MaskGIT unmasking.

    Path (rectified flow, t = 1 is data): x_t = t * x1 + (1 - t) * x0, x0 ~ N(0, I), velocity v = x1 - x0. Only the
    last frame is noised; the context frames are clean (their time embedding is t = 1). Each frame's FiLM conditioning
    is [action a_{t-1} (zeros at frame 0), embedding of its flow time], so the backbone's per-frame adaptive norms act as
    adaLN for the noise level. fm_pred 'v' regresses the velocity, 'x' predicts x1 and derives the velocity; the loss is
    the velocity MSE in both cases. Samples are rounded to the FSQ grid at the very end."""

    def __init__(self, frame_size=(128, 128), patch_size=4, embed_dim=256, num_heads=8, hidden_dim=512, num_blocks=12,
                 latent_dim=6, num_bins=4, conditioning_dim=0, time_dim=64, fm_pred="v", fm_shift=1.0, qk_norm=True,
                 t_eps=0.05):
        super().__init__()
        assert fm_pred in ("v", "x"), fm_pred
        self.fm_pred, self.fm_shift, self.t_eps = fm_pred, float(fm_shift), float(t_eps)
        self.num_bins, self.latent_dim = num_bins, latent_dim
        self.action_dim = int(conditioning_dim or 0)
        self.time_dim = time_dim
        H, W = frame_size

        self.latent_embed = nn.Linear(latent_dim, embed_dim)
        self.time_mlp = nn.Sequential(nn.Linear(time_dim, 2 * time_dim), nn.SiLU(), nn.Linear(2 * time_dim, time_dim))
        self.transformer = STTransformer(
            embed_dim, num_heads, hidden_dim, num_blocks, causal=True,
            conditioning_dim=self.action_dim + time_dim, qk_norm=qk_norm,
        )
        # zero-init output: the model starts by predicting v = 0 (or x1 = 0), as DiT's zero-init final layer
        self.output_mlp = nn.Linear(embed_dim, latent_dim)
        nn.init.zeros_(self.output_mlp.weight); nn.init.zeros_(self.output_mlp.bias)

        pe_spatial = build_spatial_only_pe((H, W), patch_size, embed_dim, device='cpu', dtype=torch.float32)  # [1,P,E]
        self.register_buffer("pos_spatial_dec", pe_spatial, persistent=False)

    def _conditioning(self, actions, t, T):
        # actions: [B, T-1, A] or None; t: [B, T] flow time per frame -> [B, T, A + Dt]
        temb = self.time_mlp(timestep_embedding(t, self.time_dim))  # [B, T, Dt]
        if self.action_dim == 0:
            return temb
        B = t.shape[0]
        if actions is None:
            a = torch.zeros(B, T, self.action_dim, device=t.device, dtype=temb.dtype)  # [B, T, A]
        else:
            # a_{t-1} drives frame t (same shift as AdaptiveNormalizer does for [B, T-1, A] conditioning)
            a = torch.cat([torch.zeros_like(actions[:, :1]), actions[:, :T - 1]], dim=1).to(temb.dtype)  # [B, T, A]
        return torch.cat([a, temb], dim=-1)  # [B, T, A + Dt]

    def net(self, latents, actions, t):
        # latents: [B, T, P, L] (last frame noisy); actions: [B, T-1, A] or None; t: [B, T] -> raw output [B, T, P, L]
        B, T, P, L = latents.shape
        emb = self.latent_embed(latents.float()) + self.pos_spatial_dec.to(latents.device)  # [B, T, P, E]
        out = self.transformer(emb, conditioning=self._conditioning(actions, t, T))  # [B, T, P, E]
        return self.output_mlp(out)  # [B, T, P, L]

    def velocity(self, latents, actions, t):
        # velocity of the last frame: [B, P, L]
        out = self.net(latents, actions, t)[:, -1]  # [B, P, L]
        if self.fm_pred == "v":
            return out
        s = (1 - t[:, -1]).clamp_min(self.t_eps)[:, None, None]  # [B, 1, 1] noise level of the target
        return (out.float() - latents[:, -1].float()) / s  # (x1_hat - x_t) / (1 - t)

    def forward(self, latents, training=True, conditioning=None, targets=None):
        # latents: [B, T, P, L] clean FSQ latents; conditioning: [B, T-1, A] actions. Returns (v_hat, None, loss) like
        # DynamicsModel.forward returns (logits, mask, loss).
        B, T, P, L = latents.shape
        x1 = latents[:, -1].float()  # [B, P, L]
        x0 = torch.randn_like(x1)  # [B, P, L]
        s = shift_noise_level(torch.rand(B, device=latents.device), self.fm_shift)  # [B] noise level
        tt = 1 - s  # [B] flow time
        xt = tt[:, None, None] * x1 + s[:, None, None] * x0  # [B, P, L]
        noisy = torch.cat([latents[:, :-1].float(), xt[:, None]], dim=1)  # [B, T, P, L]
        t = torch.ones(B, T, device=latents.device)  # [B, T] context is clean (t = 1)
        t[:, -1] = tt
        v_hat = self.velocity(noisy, conditioning, t)  # [B, P, L]
        loss = F.mse_loss(v_hat.float(), x1 - x0)
        return v_hat, None, loss

    def round_to_grid(self, x):
        # continuous latents -> nearest FSQ grid value in [-1, 1] (same grid as FiniteScalarQuantizer)
        digits = torch.round((x + 1) * 0.5 * (self.num_bins - 1)).clamp(0, self.num_bins - 1)
        return 2 * digits / (self.num_bins - 1) - 1

    @torch.no_grad()
    def sample_next(self, context_latents, conditioning, num_steps, generator=None):
        # context_latents: [B, Tc, P, L]; conditioning: [B, Tc, A] (last = transition into the new frame) or None
        # Euler integration from noise over the shifted grid; returns the rounded new frame [B, P, L]
        B, Tc, P, L = context_latents.shape
        dev = context_latents.device
        x = torch.randn(B, P, L, device=dev, generator=generator)  # [B, P, L]
        s_grid = shift_noise_level(torch.linspace(1, 0, num_steps + 1, device=dev), self.fm_shift)  # [N+1], 1 -> 0
        t = torch.ones(B, Tc + 1, device=dev)  # [B, Tc+1]
        for k in range(num_steps):
            t[:, -1] = 1 - s_grid[k]
            inp = torch.cat([context_latents.float(), x[:, None]], dim=1)  # [B, Tc+1, P, L]
            v = self.velocity(inp, conditioning, t).float()  # [B, P, L]
            x = x + (s_grid[k] - s_grid[k + 1]) * v  # dt = t_{k+1} - t_k
        return self.round_to_grid(x)

    @torch.no_grad()
    def forward_inference(self, context_latents, prediction_horizon, num_steps, index_to_latents_fn=None,
                          conditioning=None, schedule_k=None, temperature=None, generator=None):
        # same interface as DynamicsModel.forward_inference (num_steps = Euler steps; schedule_k / temperature unused)
        # context_latents: [B, T_ctx, P, L]; conditioning: [B, >= T_ctx+H-1, A] -> [B, T_ctx + H, P, L]
        latents = context_latents
        for h in range(int(prediction_horizon)):
            Tc = latents.shape[1]
            cond = None if conditioning is None else conditioning[:, :Tc]  # [B, Tc, A]
            new = self.sample_next(latents, cond, num_steps, generator=generator)  # [B, P, L]
            latents = torch.cat([latents, new[:, None].to(latents.dtype)], dim=1)
        return latents

    @property
    def model_type(self) -> str:
        return ModelType.FlowDynamicsModel
